### PR TITLE
From NumPy 1.24.0 ``np.float`` is deprecated

### PR DESCRIPTION
**Pull request by lldelisle**
I removed them to make bx-python compatible with last version of numpy but this drop support for numpy <1.20. I don't know which file I should modify.

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by lldelisle** [comment]
@nsoranzo do you know where should I restrict numpy version?

**Comment by nsoranzo** [comment]
> I removed them to make bx-python compatible with last version of numpy but this drop support for numpy <0.20

Are you sure this breaks compatibility with older numpy? And, do you mean numpy <1.20 perhaps?

**Comment by lldelisle** [comment]
Yes exactly
The new code requires numpy>=1.20

**Comment by nsoranzo** [comment]
It does seem to work in my hands as far back as numpy 1.14.5 , what error do you see?

**Comment by lldelisle** [comment]
Then perfect. I thought these changes would break... One deploy was too long, is it ok to merge like this?

**Comment by nsoranzo** [comment]
Yes, thanks, will fix the deploy separately.

**Comment by nsoranzo** [comment]
> Yes, thanks, will fix the deploy separately.

Fixed in https://github.com/bxlab/bx-python/commit/6f7e5ca3d9b4801afb2de5452a93feee5a7cedd7 . Let me know if we should do a release.

**Comment by lldelisle** [comment]
For me it is ok. Let see if people need it.

**Pull request merged**
