### PR TITLE
Restore NiceReaderWrapper.current_line

### PR DESCRIPTION
**Pull request by mvdbeek**
This is accessed in many downstream tools and in bx-python itself.

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
@mvdbeek How do you like this version? I've also added a comment and a doctest to prevent accidental removal in the future.

**Comment by mvdbeek** [comment]
Yeah, looks good!

**Comment by mvdbeek** [comment]
Could you tag a new release as well ?

**Comment by nsoranzo** [comment]
Done and uploaded to PyPI.

**Pull request merged**
