### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by mbargull**
This simply replaces `PyString_*` C-API references with `PyBytes_*` which are the corresponding ones for Python 3. `PyBytes` is also available in Python 2.6/2.7 as an alias to `PyString` to provide forward compatibility. With those changes a Conda package could be successfully built for Python 2 and 3 from the Bioconda recipe: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bx-python/.
The changeset was created by `find lib -name '*.pyx' -exec sed -i s/PyString_/PyBytes_/g {} ';'`.
I am not familiar with the code base so please review whether all `PyString_`-replacements are accurate, i.e., the corresponding code deals with `bytes` instead of `str` (or `str` instead of `unicode` in Python 2 terms).

To make it build for the Bioconda package I also had to remove the outdated Cython `.c` files (via `
find lib -name '*.pyx' | sed 's/\.pyx$/\.c/' | xargs rm`). If you strongly insist on recreating them, I can do that. Though I would advice against it since they needn't be under source control and are always bound to get out of sync again. They could/should be recreated on-the-fly when building the distribution, i.e., `python setup.py build_ext sdist` for source distributions.

### CODE REVIEW

**Comment by mbargull** [comment]
Some tests are failing. And I'm blind and somehow didn't see #15 ..

**Comment by mbargull** [comment]
All tests pass (including `bx/, script_tests/` for `nosetest`) under Python 2.7, 3.3 and (locally) 3.6.

**Comment by mbargull** [comment]
Please review as I did not check every single use of `str`/`""`/`''`/`StringIO` etc., e.g., I (apart from the merged commit) didn't touch `bx.align.lav` (uses `StringIO`) at all.

**Comment by nsoranzo** [comment]
Very nice @mbargull, thanks a lot for completing my initial effort!

@jxtx Can you review/merge this? It's one of the last stumbling blocks to running Galaxy under Python3.

**Comment by jxtx** [comment]
Sweet!

**Comment by mbargull** [comment]
Hey there, please still note
https://github.com/bxlab/bx-python/pull/25#issuecomment-343258721:
> Please review as I did not check every single use of `str`/`""`/`''`/`StringIO` etc., e.g., I (apart from the merged commit) didn't touch `bx.align.lav` (uses `StringIO`) at all.

**Comment by jxtx** [comment]
Tests are passing under 2 and 3 so I don't want to hold this up. We can fix problems as they arise. Hard to review code nobody has touched in a decade ;)

**Comment by nsoranzo** [comment]
@jxtx Thanks a lot! Can you also do GitHub and PyPI releases? That would probably require the compilation of .c files from the .pyx ones with Cython.

**Comment by mbargull** [comment]
A `python setup.py build_ext sdist` should get you set on those Cython files.

**Comment by rsharris** [comment]
@mbargull Regarding bx.align.lav -- Is there any good reason to try to support lav moving forward?

Undoubtedly I wrote the original of that (but don't know if what I wrote has any resemblance to what's there now).  I'm not up on python3.  What's the issue with StringIO?

I wonder what fraction of the user base is using lav (if any?).  This was the output format of blastz.  Blastz was replaced by lastz 10 years ago.  Lastz supports many other formats, and almost all of them are more useful than lav for downstream analysis.

I suspect the only people using lav are those using legacy pipelines.  The two pipelines I'm aware of are multiz and the UCSC multiple alignment stuff.  But is there any intersection between those users and bx python users?

Another issue with lav is that many early lav producers had minor differences in what the format was. The format evolved for several years before a spec was written circa 2008.  Differences in reporting genomic positions exist (especially when the producer was working with a subinterval of a chromosome).

**Comment by mbargull** [comment]
> I'm not up on python3. What's the issue with StringIO?

It's only that with Python 3 `str` and `StringIO` use Unicode encoded strings, i.e., the Python 2 `unicode` type. So with Python 3 you have to distinguish whether you want to operate on text strings (Python 3 `str` type which is Python 2's `unicode`) or binary strings (Python 3 `bytes` type which is Python 2's `str`). The legacy code might use `StringIO` in binary string contexts where you'd have to change that to `BytesIO` for Python 3.
The gist is that to port Python 2 code to Python 3 you have to closely look at the intended uses (text vs. binary) of string types (`str`/`""`/`''`/`StringIO`).

As for `lav` and `bx-python` in general: TBH, I don't really know much about the project and was only carried away when trying out some Cython-related things 😉. I was made aware of the missing Python 3 support by https://github.com/bioconda/bioconda-recipes/issues/2288 and https://github.com/bioconda/bioconda-recipes/pull/6619.

**Comment by rsharris** [comment]
Looking at lav.py, it's only using StringIO for text.  And it's "" if that matters.

It's using StringIO to create a fasta sequence full of "n"s, IF it wasn't able to open the real file AND IF a instance flag tells it that's the appropriate action.

The odd thing (to me) is it tries to open the real file as binary.  Not sure why it wouldn't open it as text, since fasta would normally be considered a text-only format.  Perhaps it opens it as binary so it can deal with files written with either type of line endings.

**Pull request merged**
