### PR TITLE
StopIteration fix

### LINKED ISSUE #56: StopIteration transformed to RuntimeError on python >= 3.7
This is due to https://www.python.org/dev/peps/pep-0479/

```
Traceback (most recent call last):
  File "/Users/mvandenb/miniconda3/envs/__bx-python@0.8.6/lib/python3.7/site-packages/bx/intervals/io.py", line 234, in iterwrapper
    self.current_line = next(self.input_wrapper)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mvandenb/src/galaxy/lib/galaxy/datatypes/converters/interval_to_bedstrict_converter.py", line 155, in <module>
    __main__()
  File "/Users/mvandenb/src/galaxy/lib/galaxy/datatypes/converters/interval_to_bedstrict_converter.py", line 132, in __main__
    for count, region in enumerate(bx.intervals.io.NiceReaderWrapper(fh, chrom_col=chromCol, start_col=startCol, end_col=endCol, strand_col=strandCol, fix_strand=True, return_header=False, return_comments=False)):
  File "/Users/mvandenb/miniconda3/envs/__bx-python@0.8.6/lib/python3.7/site-packages/bx/intervals/io.py", line 221, in __next__
    nextitem = super(NiceReaderWrapper, self).__next__()
  File "/Users/mvandenb/miniconda3/envs/__bx-python@0.8.6/lib/python3.7/site-packages/bx/tabular/io.py", line 105, in __next__
    line = next(self.input_iter)
RuntimeError: generator raised StopIteration
```

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes #56

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think this would be a better fix:
```diff
diff --git a/lib/bx/intervals/io.py b/lib/bx/intervals/io.py
index aedc720..1a3b6a8 100644
--- a/lib/bx/intervals/io.py
+++ b/lib/bx/intervals/io.py
@@ -207,8 +207,7 @@ class NiceReaderWrapper(GenomicIntervalReader):
         GenomicIntervalReader.__init__(self, reader, **kwargs)
         self.outstream = kwargs.get("outstream", None)
         self.print_delegate = kwargs.get("print_delegate", None)
-        self.input_wrapper = iter(self.input)
-        self.input_iter = self.iterwrapper()
+        self.input_iter = iter(self.input)
         self.skipped = 0
         self.skipped_lines = []
 
@@ -229,11 +228,6 @@ class NiceReaderWrapper(GenomicIntervalReader):
                 if self.skipped < 10:
                     self.skipped_lines.append((self.linenum, self.current_line, str(e)))
 
-    def iterwrapper(self):
-        while True:
-            self.current_line = next(self.input_wrapper)
-            yield self.current_line
-
 
 class BitsetSafeReaderWrapper(NiceReaderWrapper):
     def __init__(self, reader, lens={}):
```

Should I push that to your branch?

**Comment by mvdbeek** [comment]
sure!

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
@mvdbeek Need a new bx-python release?

**Comment by mvdbeek** [comment]
that would be great!

**Pull request merged**
