### PR TITLE
Improve maf handling

### PR DESCRIPTION
**Pull request by lldelisle**
I improved 'e' lines handling in maf.
I added tests for main methods.
 (The two next parts have not been checked).
I simplified some scripts to use method instead of external function
I use `parse_e_rows=True` is much more scripts.

All comments are welcome

### CODE REVIEW

**Comment by lldelisle** [comment]
I think it is ready for review.

**Comment by nsoranzo** [comment]
I've fixed the issue in the "Deploy" CI jobs, if you want to rebase/merge the "main" branch.

**Comment by lldelisle** [comment]
Hi,
All checks passed in case you have time to review.

**Comment by lldelisle** [comment]
Hi there,
Still interested in this PR in case.

**Comment by nsoranzo** [comment]
@lldelisle Thanks again for the PR and sorry it took so long to merge, I guess at this point you are the person that knows more about this part of the code! Please let me know if:
- you'd like a new release with this included
- you are interested in joining the maintenance team of bx-python

**Comment by lldelisle** [comment]
Hi,
Thanks for the merge.
- Yes I would like a new release as I would like this to be included in the galaxy tool and in pyGenomeTracks.
- If you think I can help, I would be happy to be part of the maintenance team.

**Comment by nsoranzo** [comment]
@lldelisle New bx-python 0.8.13 is out, and thanks for joining the maintenance team!

**Comment by lldelisle** [comment]
Thanks to you...

**Pull request merged**
